/* cellrenderertextish.h generated by valac 0.40.23, the Vala compiler, do not modify */


#ifndef __CELLRENDERERTEXTISH_H__
#define __CELLRENDERERTEXTISH_H__

#include <glib.h>
#include <gtk/gtk.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>

G_BEGIN_DECLS


#define TYPE_CELL_RENDERER_TEXTISH (cell_renderer_textish_get_type ())
#define CELL_RENDERER_TEXTISH(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CELL_RENDERER_TEXTISH, CellRendererTextish))
#define CELL_RENDERER_TEXTISH_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CELL_RENDERER_TEXTISH, CellRendererTextishClass))
#define IS_CELL_RENDERER_TEXTISH(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CELL_RENDERER_TEXTISH))
#define IS_CELL_RENDERER_TEXTISH_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CELL_RENDERER_TEXTISH))
#define CELL_RENDERER_TEXTISH_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CELL_RENDERER_TEXTISH, CellRendererTextishClass))

typedef struct _CellRendererTextish CellRendererTextish;
typedef struct _CellRendererTextishClass CellRendererTextishClass;
typedef struct _CellRendererTextishPrivate CellRendererTextishPrivate;
typedef enum  {
	CELL_RENDERER_TEXTISH_MODE_Text,
	CELL_RENDERER_TEXTISH_MODE_Key,
	CELL_RENDERER_TEXTISH_MODE_Popup,
	CELL_RENDERER_TEXTISH_MODE_Combo
} CellRendererTextishMode;


#define CELL_RENDERER_TEXTISH_TYPE_MODE (cell_renderer_textish_mode_get_type ())

struct _CellRendererTextish {
	GtkCellRendererText parent_instance;
	CellRendererTextishPrivate * priv;
	CellRendererTextishMode mode;
	gchar** items;
	gint items_length1;
};

struct _CellRendererTextishClass {
	GtkCellRendererTextClass parent_class;
};


GType cell_renderer_textish_get_type (void) G_GNUC_CONST;
GType cell_renderer_textish_mode_get_type (void) G_GNUC_CONST;
CellRendererTextish* cell_renderer_textish_new (void);
CellRendererTextish* cell_renderer_textish_construct (GType object_type);
CellRendererTextish* cell_renderer_textish_new_with_items (gchar** items,
                                                           int items_length1);
CellRendererTextish* cell_renderer_textish_construct_with_items (GType object_type,
                                                                 gchar** items,
                                                                 int items_length1);


G_END_DECLS

#endif
