#!/bin/bash
VERSION=`git describe`
DIST=easystroke-$VERSION
TGZ=$DIST.tar.gz

git archive --format=tar --prefix=$DIST/ HEAD | (cd /tmp && tar x)
cd /tmp
echo $VERSION > $DIST/version
rm $DIST/.gitignore $DIST/release
if whiptail --yesno "create and upload $TGZ?" 7 70; then
	tar czf $TGZ $DIST
	rsync -avP $TGZ thjaeger@frs.sourceforge.net:uploads/
	rm $TGZ
fi
if whiptail --yesno "create snapshot?" 7 70; then
	pushd $DIST
	make -j2
	strip -s easystroke
	gzip easystroke
	popd
	mv $DIST/easystroke.gz $DIST.gz
fi
rm -R $DIST
