#!/bin/bash
VERSION=`git describe`
DIST=easystroke-$VERSION
TGZ=$DIST.tar.gz

whiptail --yesno "create and upload $TGZ?" 7 70 || exit 0
git archive --format=tar --prefix=$DIST/ HEAD | (cd /tmp && tar x)
pushd /tmp
echo $VERSION > $DIST/version
tar czf $TGZ $DIST
popd

rsync -avP /tmp/$TGZ thjaeger@frs.sourceforge.net:uploads/
rm -R /tmp/$DIST /tmp/$TGZ
