#!/bin/bash
if [ "x$1" = "x" ]; then
  echo "Error: you forgot to supply a dist name"
  exit 1
fi
DIST=easystroke-$1
echo $DIST

mkdir upload

# tar.gz
git archive --format=tar --prefix=$DIST/ $1 | gzip > upload/$DIST.tar.gz

# binary .gz
mkdir build
pushd build
tar -xzf ../upload/$DIST.tar.gz
cd $DIST
make -j2 static
mv easystroke $DIST
gzip $DIST
mv $DIST.gz ../../upload
popd
rm -R build

rsync -avP upload/* thjaeger@frs.sourceforge.net:uploads/
rm -R upload
